apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service1.name }}-svc
  labels:
    myapp.io/name: {{ .Values.service1.name }}
spec:
  type: {{ .Values.service1.type }}
  ports:
    - port: {{ .Values.service1.port }}
      targetPort: {{ .Values.service1.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.service1.name }}
