{{- if .Values.service1.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.service1.name }}-sa
  labels:
    myapp.io/name: {{ .Values.service1.name }}
{{- end }}