#service 1 configuration
service1:
  type: Nodeport
  port: 80
  targetPort: 8080
  name: service1
  replicas: 2
  image: nginxdemos/nginx-hello:plain-text
  pullPolicy: IfNotPresent
  # use default serviceAccount
  ressources:
    limites:
      cpu: 2000m
      memory: 64Mi
    requests:
      cpu: 200m
      memory: 32Mi
  serviceAccount:
    # Specifies whether a service account should be created
    create: false
  # Annotations to add to the service account
    name: default
  hpa:
    enabled: false
    #minReplicas: 1
    #maxReplicas: 6
    #targetCPUUtilizationPercentage: 70
    #targetMemoryUtilizationPercentage: 90
  
  #service 2 configuration
service2:
  type: LoadBalancer
  port: 80
  targetPort: 8080
  name: service2
  image: nginxdemos/nginx-hello:plain-text
  pullPolicy: IfNotPresent
  ressources:
    limites:
      cpu: 1000m
      memory: 32Mi
    requests:
      cpu: 100m
      memory: 16Mi
  # use service2 serviceAccount
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
  # Annotations to add to the service account
    name: SA-service2
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 6
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 90



ingress:
  enabled: true
  className: nginx
  hosts:
  - host: service.myapp.com
    paths:
    - path: /service1
      pathType: Prefix
      backend:
        service:
          name: service1
          port:
            number: 80
    - path: /service2
      pathType: Prefix
      backend:
        service:
          name: service2
          port:
            number: 80
  tls: 
  - hosts:
    - service.myapp.com
    secretName: myapp-secret


#create more pod when exceed 70%cpu and 90% mem
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 90


#no need for sample demonstration
nodeSelector: {}
tolerations: []
affinity: {}
podSecurityContext: {}
  # fsGroup: 2000
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000


