apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: default
  template:
    metadata:
      labels:
        app: default
    spec:
      containers:
      - name: default-img
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
          - name: foo
            mountPath: "/usr/share/nginx/html/"    
      volumes:
      - name: foo
        configMap:
          name: {{ .Chart.Name }}-configmap

---
apiVersion: v1
kind: Service
metadata:
  name: default-svc
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: default