{{- if .Values.service2.hpa.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.service2.name }}-hpa
  labels:
    myapp.io/name: {{ .Values.service2.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.service2.name }}-deploy
  minReplicas: {{ .Values.service2.hpa.minReplicas }}
  maxReplicas: {{ .Values.service2.hpa.maxReplicas }}
  metrics:
    {{- if .Values.service2.hpa.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.service2.hpa.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.service2.hpa.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.service2.hpa.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
