{{- if .Values.service2.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.service2.name }}-sa
  labels:
    myapp.io/name: {{ .Values.service2.name }}
 {{- end }}