apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service2.name }}-svc
  labels:
    myapp.io/name: {{ .Values.service2.name }}
spec:
  type: {{ .Values.service2.type }}
  ports:
    - port: {{ .Values.service2.port }}
      targetPort: {{ .Values.service2.targetPort }}
      protocol: TCP
      name: http
  selector:
    myapp.io/name: {{ .Values.service2.name }}
