{{- if .Values.service1.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.service1.serviceAccount.name }}
  labels:
    myapp.io/name: {{- Values.service1.name }}
    myapp.io/svcName: {{- Values.service1.svcName }}
